source 'https://rubygems.org'

#ruby=ruby-3.0.0
ruby '3.0.0'

gem 'rspec'
gem 'rest-client'
gem 'rspec_junit_formatter'
gem 'httplog'
gem 'net_http_ssl_fix'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rspec-mocks'
gem 'rspec-support'
gem 'ruby-kafka'
gem 'specific_install'
gem 'nokogiri'