log-level: info
oidc-issuer: "https://us-east.appid.cloud.ibm.com/oauth/v4/0f389ea4-778e-4831-9b29-6156c4c1df1e"
jwt-audience-id: 21e7d376-9cdb-4a9d-a11f-9b76c007244d
validation: true
elastic-url: https://c9acb36a-0feb-4b6e-aac1-6651c71d19e4.2adb0220806343e3ae11df79c89b377f.databases.appdomain.cloud:32085
elastic-username: a-username
elastic-password: a-password
elastic-cert: |
  -----BEGIN CERTIFICATE-----
  MIIDHTCCAgWgAwIBAgIUL5g6t1HmNOt8OOqUWyuQZeWsrUAwDQYJKoZIhvcNAQEL
  BQAwHjEcMBoGA1UEAwwTSUJNIENsb3VkIERhdGFiYXNlczAeFw0xODExMjExMTQ3
  MjdaFw0yODExMTgxMTQ3MjdaMB4xHDAaBgNVBAMME0lCTSBDbG91ZCBEYXRhYmFz
  ZXMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC3hxfosYeXdmrQRHlU
  vMg91IWSCuGZ16RbHbZ2p62SEUfBJemr4MkTr48YZTfiTCZjckWWGlBlvUYr0cYY
  KM3OPtkhk3lmkAQlJcMCPfiF2+mBxAUqrIibCgmQijylRJW4sEFQgSbrXewDywEd
  8JUgm+82DwLYy6vnkKJjzcUZk5OKS1Uv7w0pHUtUMtNLaSyKksDdE9d9sj6lWTFJ
  W9CyXCp5iffJ97oewIh47nIFYU5D5MptCDYr6wifOWvhiduYD6WMR7wDgLMv/ra9
  Zt4nt7MYglRmKnO77DZI5Y9lT4gw4FiU0k65aWnXrk+1DZ4jqFdWk3VpoXhA0IuX
  ZMbPAgMBAAGjUzBRMB0GA1UdDgQWBBQYWTX4dsUL3/LnQAXQLLzh46yDATAfBgNV
  HSMEGDAWgBQYWTX4dsUL3/LnQAXQLLzh46yDATAPBgNVHRMBAf8EBTADAQH/MA0G
  CSqGSIb3DQEBCwUAA4IBAQAPwYrOIQMEreNuHY/68lFJimB6GCinGsJw8YIBBQwA
  tdJMOXU8bXGrEHEuZ6Qaho7Q5dV2bB6GVKTMqhSEdrvuyxKniQ90jdkQSk2VHhDe
  H+6i04hA9TkKT6ooLwMPc1LYYzqDljEkfKlLIPWCkOAozD3cyc26pV/35nG7WzAF
  xw7S3jAyB3WcJDlWlSWGTn58w3EHxzVXvKT6Y9eAdKp4SjUHyVFsL5xtSyjH8zpF
  pZKK8wWNUwgWQ66MNh8Ckq732JZ+so6RAfb4BbNj45I3s9fuZSYlvjkc5/+da3Ck
  Rp6anX5N6yIrzhVmAgefjQdBztYzdfPhsJBkS/TDnRmk
  -----END CERTIFICATE-----
elastic-crn: "crn:v1:bluemix:public:databases-for-elasticsearch:us-east:a/52366c9ab214402f9e96917b1b2850e9:c9acb36a-0feb-4b6e-aac1-6651c71d19e4::"
kafka-admin-url: https://twvyj4m0kft5j0mh.svc01.us-east.eventstreams.cloud.ibm.com
kafka-properties:
  - "security.protocol:sasl_ssl"
  - "sasl.mechanism:PLAIN"
  - "sasl.username:token"
  - "sasl.password:a-password"
  - "ssl.endpoint.identification.algorithm:https"

kafka-brokers:
  - "broker-4-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093"
  - "broker-3-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093"
  - "broker-2-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093"
  - "broker-5-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093"
  - "broker-1-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093"
  - "broker-0-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093"
mongoDb-uri: mongo-uri
mongoDb-name: "HRI-DEV"
mongoCol-name: "HRI-Mgmt"
az-oidc-issuer: https://sts.windows.net/ceaa63aa-5d5c-4c7d-94b0-02f9a3ab6a8c/
az-jwt-audience-id: "c33ac4da-21c6-426b-abcc-27e24ff1ccf9"
az-kafka-brokers:
- "wn3-tst-ea.luiuer1npb0uhpa3hpish513wd.bx.internal.cloudapp.net"
- "wn2-tst-ea.luiuer1npb0uhpa3hpish513wd.bx.internal.cloudapp.net"
- "wn1-tst-ea.luiuer1npb0uhpa3hpish513wd.bx.internal.cloudapp.net"
- "wn0-tst-ea.luiuer1npb0uhpa3hpish513wd.bx.internal.cloudapp.net"