log-level: info
az-oidc-issuer: https://sts.windows.net/ceaa63aa-5d5c-4c7d-94b0-02f9a3ab6a8c/
az-jwt-audience-id: "c33ac4da-21c6-426b-abcc-27e24ff1ccf9"
validation: true
mongoDb-uri: "mongodb://hi"
mongoDb-name: "HRI-DEV"
mongoCol-name: "HRI-Mgmt"
az-kafka-properties:
  - "security.protocol:sasl_ssl"
  - "sasl.mechanism:PLAIN"
  - "sasl.username:kafkaUsername"
  - "sasl.password:KafkaAdmin-password"
  - "ssl.endpoint.identification.algorithm:https"

ca-location: "./client.cert.pem/cert"  

az-kafka-brokers:
  - "broker 1"
  - "broker 2" 
  - "broker 3"
  - "broker 4"