# oidc-issuer: "https://us-south.appid.cloud.ibm.com/oauth/v4/ec9bcf93-4863-46a7-bf66-19009b4e2ed8"
jwt-audience-id: "b8f85fbe-b00a-4296-b54b-e9ec09a5b2f3"
validation: true
# elastic-url: "https://elastic.com"
# elastic-username: "elasticUsername"
# elastic-password: "elasticPassword"
# elastic-cert: |
#   -----BEGIN CERTIFICATE-----
#   MIIDDzCCAfegAwIBAgIJANEH58y2/kzHMA0GCSqGSIb3DQEBCwUAMB4xHDAaBgNV
#   BAMME0lCTSBDbG91ZCBEYXRhYmFzZXMwHhcNMTgwNjI1MTQyOTAwWhcNMjgwNjIy
#   MTQyOTAwWjAeMRwwGgYDVQQDDBNJQk0gQ2xvdWQgRGF0YWJhc2VzMIIBIjANBgkq
#   hkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8lpaQGzcFdGqeMlmqjffMPpIQhqpd8qJ
#   Pr3bIkrXJbTcJJ9uIckSUcCjw4Z/rSg8nnT13SCcOl+1to+7kdMiU8qOWKiceYZ5
#   y+yZYfCkGaiZVfazQBm45zBtFWv+AB/8hfCTdNF7VY4spaA3oBE2aS7OANNSRZSK
#   pwy24IUgUcILJW+mcvW80Vx+GXRfD9Ytt6PRJgBhYuUBpgzvngmCMGBn+l2KNiSf
#   weovYDCD6Vngl2+6W9QFAFtWXWgF3iDQD5nl/n4mripMSX6UG/n6657u7TDdgkvA
#   1eKI2FLzYKpoKBe5rcnrM7nHgNc/nCdEs5JecHb1dHv1QfPm6pzIxwIDAQABo1Aw
#   TjAdBgNVHQ4EFgQUK3+XZo1wyKs+DEoYXbHruwSpXjgwHwYDVR0jBBgwFoAUK3+X
#   Zo1wyKs+DEoYXbHruwSpXjgwDAYDVR0TBAUwAwEB/zANBgkqhkiG9w0BAQsFAAOC
#   AQEAJf5dvlzUpqaix26qJEuqFG0IP57QQI5TCRJ6Xt/supRHo63eDvKw8zR7tlWQ
#   lV5P0N2xwuSl9ZqAJt7/k/3ZeB+nYwPoyO3KvKvATunRvlPBn4FWVXeaPsG+7fhS
#   qsejmkyonYw77HRzGOzJH4Zg8UN6mfpbaWSsyaExvqknCp9SoTQP3D67AzWqb1zY
#   doqqgGIZ2nxCkp5/FXxF/TMb55vteTQwfgBy60jVVkbF7eVOWCv0KaNHPF5hrqbN
#   i+3XjJ7/peF3xMvTMoy35DcT3E2ZeSVjouZs15O90kI3k2daS2OHJABW0vSj4nLz
#   +PQzp/B9cQmOO8dCe049Q3oaUA==
#   -----END CERTIFICATE-----
# elastic-crn: "elasticCrn"
kafka-admin-url: "https://ibm.kafka.com"
# kafka-brokers:
#   - "broker 1"
#   - "broker 2"
az-kafka-brokers:
  - "broker 1"
  - "broker 2"
# kafka-properties:
#   - "sasl.mechanism:PLAIN"
#   - "sasl.username:kafkaUsername"
#   - "sasl.password:kafkaPassword"
# new-relic-enabled: true
# new-relic-app-name: "nrAppName"
# New relic License Keys have to be 40 characters long
# new-relic-license-key: "nrLicenseKey0000000000000000000000000000"
tls-enabled: true
tls-cert-path: "./server-cert.pem"
tls-key-path: "./server-key.pem"
mongoDb-uri: "mongodb://hi"
mongoDb-name: "HRI-DEV"
mongoCol-name: "HRI-Mgmt"
az-oidc-issuer: https://sts.windows.net/ceaa63aa-5d5c-4c7d-94b0-02f9a3ab6a8c/
az-jwt-audience-id: "c33ac4da-21c6-426b-abcc-27e24ff1ccf9"