validation: true
az-kafka-brokers:
  - "broker 1"
  - "broker 2"
new-relic-enabled: true
new-relic-app-name: "nrAppName"
# New relic License Keys have to be 40 characters long
new-relic-license-key: "nrLicenseKey0000000000000000000000000000"
tls-enabled: true
tls-cert-path: "./server-cert.pem"
tls-key-path: "./server-key.pem"
mongoDb-uri: "mongodb://hi"
mongoDb-name: "HRI-DEV"
mongoCol-name: "HRI-Mgmt"
az-oidc-issuer: https://sts.windows.net/ceaa63aa-5d5c-4c7d-94b0-02f9a3ab6a8c/
az-jwt-audience-id: "c33ac4da-21c6-426b-abcc-27e24ff1ccf9"