{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "mgmt-api.fullname" . }}-ingress
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    
    {{- if .Values.security.tls.enabled }}
    nginx.ingress.kubernetes.io/proxy-ssl-secret: "{{ .Release.Namespace }}/{{ .Values.security.tls.secretName }}"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "true"
    {{- end }}

spec:
  ingressClassName: nginx
{{- if .Values.ingress.tlsSecretName }}
  tls:
  - hosts:
      - {{ .Values.ingress.host | quote }}
    secretName: {{ .Values.ingress.tlsSecretName }}
{{- end }}
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hri-mgmt-api
            port:
              number: {{ if .Values.security.tls.enabled }}443{{ else }}80{{ end }}
{{- end }}
