/**
 * (C) Copyright IBM Corp. 2020
 *
 * SPDX-License-Identifier: Apache-2.0
 */
package batches

import (
	"github.com/Alvearie/hri-mgmt-api/common/param"
	"github.com/Alvearie/hri-mgmt-api/common/param/esparam"
	"strings"
)

const (
	inputSuffix        string = ".in"
	notificationSuffix string = ".notification"
	batchIdSuffix      string = "batch"
)

func EsDocToBatch(esDoc map[string]interface{}) map[string]interface{} {
	batch := esDoc["_source"].(map[string]interface{})
	batch[param.BatchId] = EsDocIdToBatchId(esDoc[esparam.EsDocId].(string))
	return batch
}

/*
A suffix is appended to the document Id's generated by Elastic Search for batches due to a bug in the IBM Functions
API Gateway. The API Gateway drops any trailing '-' characters from the url, so when the document Id ends in '-', the
API Gateway drops it causing 'document not found' errors in Elastic Search calls. A cloud support ticket was
created, but it has not been fixed: https://cloud.ibm.com/unifiedsupport/cases/manage/CS1724821?accountId=49f48a067ac4433a911740653049e83d
If this is ever fixed, the suffix can be removed and batch ids can just be the Elastic Search document Id.
*/

func BatchIdToEsDocId(batchId string) string {
	return strings.TrimSuffix(batchId, batchIdSuffix)
}

func EsDocIdToBatchId(docId string) string {
	return docId + batchIdSuffix
}

// Notification topic will be inferred from inputTopic using the following logic:
// If inputTopic ends with the ".in" suffix, then the suffix will be replaced with ".notification",
// If inputTopic does not end with the ".in" suffix, then ".notification" will just be appended to inputTopic
func InputTopicToNotificationTopic(inputTopic string) string {
	return strings.TrimSuffix(inputTopic, inputSuffix) + notificationSuffix
}
