name: CI Workflow

on:
  push:
    branches: [ '**' ]
  workflow_dispatch:

concurrency: ci-${{ github.ref }}

jobs:

  build:
    name: Build and Test
    runs-on: ubuntu-latest
    env:
      API_SPEC_DEV_BRANCH: testQA
      API_SPEC_TAG:
      APPID_TENANT: 0f389ea4-778e-4831-9b29-6156c4c1df1e
      APPID_URL: https://us-east.appid.cloud.ibm.com
      ELASTIC_CRN: "crn:v1:bluemix:public:databases-for-elasticsearch:us-east:a/52366c9ab214402f9e96917b1b2850e9:c9acb36a-0feb-4b6e-aac1-6651c71d19e4::"
      ELASTIC_URL: https://c9acb36a-0feb-4b6e-aac1-6651c71d19e4.2adb0220806343e3ae11df79c89b377f.databases.appdomain.cloud:32085
      ES_ADMIN_URL: https://twvyj4m0kft5j0mh.svc01.us-east.eventstreams.cloud.ibm.com
      HRI_URL: https://localhost:1323/hri
      IAM_CLOUD_URL: https://iam.cloud.ibm.com
      JWT_AUDIENCE_ID: 21e7d376-9cdb-4a9d-a11f-9b76c007244d
      KAFKA_BROKERS: broker-0-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-1-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-2-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-3-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-4-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093,broker-5-twvyj4m0kft5j0mh.kafka.svc01.us-east.eventstreams.cloud.ibm.com:9093
      KAFKA_INSTANCE: hri-dev1-event-streams
      TENANT_ID: test
      COS_URL: https://s3.us-east.cloud-object-storage.appdomain.cloud

      CLOUD_API_KEY: $eyJraWQiOiIyMDIyMDcxNTA4MjYiLCJhbGciOiJSUzI1NiJ9.eyJpYW1faWQiOiJJQk1pZC02NjEwMDNPRTRFIiwiaWQiOiJJQk1pZC02NjEwMDNPRTRFIiwicmVhbG1pZCI6IklCTWlkIiwic2Vzc2lvbl9pZCI6IkMtYTVkYzMzOTctNGVmNy00M2ViLWJmZjAtN2M4ZGUyMTU1NzM3Iiwic2Vzc2lvbl9leHBfbWF4IjoxNjYwMjk4ODY1LCJzZXNzaW9uX2V4cF9uZXh0IjoxNjYwMjE5NjkzLCJqdGkiOiJkNTkxOWIxMC1lODg4LTRjOTUtYWM5Yi0wMjc5NWUxY2M1MzYiLCJpZGVudGlmaWVyIjoiNjYxMDAzT0U0RSIsImdpdmVuX25hbWUiOiJMYXRoYSIsImZhbWlseV9uYW1lIjoiR2FuamkiLCJuYW1lIjoiTGF0aGEgR2FuamkiLCJlbWFpbCI6ImxnYW5qaUBtZXJhdGl2ZS5jb20iLCJzdWIiOiJsZ2FuamlAbWVyYXRpdmUuY29tIiwiYXV0aG4iOnsic3ViIjoibGdhbmppQG1lcmF0aXZlLmNvbSIsImlhbV9pZCI6IklCTWlkLTY2MTAwM09FNEUiLCJuYW1lIjoiTGF0aGEgR2FuamkiLCJnaXZlbl9uYW1lIjoiTGF0aGEiLCJmYW1pbHlfbmFtZSI6IkdhbmppIiwiZW1haWwiOiJsZ2FuamlAbWVyYXRpdmUuY29tIn0sImFjY291bnQiOnsiYm91bmRhcnkiOiJnbG9iYWwiLCJ2YWxpZCI6dHJ1ZSwiYnNzIjoiNTIzNjZjOWFiMjE0NDAyZjllOTY5MTdiMWIyODUwZTkiLCJpbXNfdXNlcl9pZCI6IjEwMTE1MDcwIiwiaW1zIjoiMjI5MzE0MiJ9LCJpYXQiOjE2NjAyMTI0OTMsImV4cCI6MTY2MDIxMzY5MywiaXNzIjoiaHR0cHM6Ly9pYW0uY2xvdWQuaWJtLmNvbS9pZGVudGl0eSIsImdyYW50X3R5cGUiOiJ1cm46aWJtOnBhcmFtczpvYXV0aDpncmFudC10eXBlOnBhc3Njb2RlIiwic2NvcGUiOiJpYm0gb3BlbmlkIiwiY2xpZW50X2lkIjoiYngiLCJhY3IiOjEsImFtciI6WyJwd2QiXX0.aISWQllfsQGSYwglDP_pSM5RAo2ed7CDb1nQu11mo_mq1ahfRSgZsGSi450pYrStIHck_9IRbtNyTPBuNX8gtuFGww21qB0pJ0hXdrNQpWErADTqD6PmqVFiqwM3qAngl33kfbe4w0DJmEyAvIH9rgUMFA6DQkb2v-_tvj1B91K1ZhPI-kXq4qKIXHzo0KWkgQnC2gDRWjScLvxAadJMIGi3WstFyOQvn2Oe4QGjXCTxbmrSJa27oaUD6cVHvjJ7fXSaFv5HUyyyKLvxBHV0ZIln3xmcoEoxtyTCU_83Vp-sRwt4Kowse3xeIq1tGCsF85bnhnP8aKcKdUTVXifucQ
      ELASTIC_PASSWORD: $a7ec2c89db5274978307b603f6b6d132825fbac81e9e71122d2b59ab259fea68
      ELASTIC_USERNAME: $ibm_cloud_1a27be2f_c7eb_4395_9cc4_71940b7f75d8
      KAFKA_PASSWORD: $dOarCwEG8iyPwmc5f2Ywj4TvjGrSCyE0pKDW_bGFomfC

    steps:
      - name: Set testQA
        uses: nelonoel/branch-name@v1.0.1

      - name: Install Go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Copyright Check
        run: ./copyrightCheck.sh

      - name: Build HRI Executable and Run Unit Tests
        run: make

      - name: Run Smoke Tests
        run: ./run-smoketests.sh

      - name: Install Ruby 3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: false

      - name: Install Ruby Gems, Run Dredd Tests, and Run IVT
        run: |
          gem install bundler
          BUNDLE_GEMFILE="./test/Gemfile" bundle install
          gem specific_install -l https://github.com/Alvearie/hri-test-helpers.git main
          gem install dredd_hooks
          ./run-dreddtests.sh
          curl -sL https://ibm.biz/idt-installer | bash
          ibmcloud login --apikey $CLOUD_API_KEY -r us-east || { echo 'IBM Cloud CLI login failed!'; exit 1; }
          ibmcloud plugin install event-streams
          ibmcloud es init -i ${KAFKA_INSTANCE}
          ./run-ivttests.sh

      - name: Archive Logs
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: hri-logs
          path: test/logs/*
          retention-days: 7

      - name: Upload Test Results
        if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/support-'))
        run: |
          ./combine_ivt_results.sh
          ./test/spec/upload_test_reports.rb IVT
          ./test/spec/upload_test_reports.rb Dredd

      - name: Post Slack Update
        if: ${{ failure() && ( github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/heads/support-') ) }}
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: "{\"Repo\":\"${{ github.repository }}\",\"Workflow\":\"${{ github.workflow }}\",\"Branch\":\"${{ env.BRANCH_NAME }}\",\"Link\":\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  docker-build:
    name: Docker Build
    needs: build
    if: ${{ github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mgmt-api
      TOOLCHAIN_ID: c0627e8e-ac25-4145-9bae-e931b1247416

    steps:
      - uses: actions/checkout@v2

      - name: Determine Image Name & Tag
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo IMAGE_ID=$IMAGE_ID:$VERSION
          echo "IMAGE_ID=$IMAGE_ID:$VERSION" >> $GITHUB_ENV

      - name: Build image
        run: docker build . --file docker/Dockerfile --tag $IMAGE_ID --label "runnumber=${GITHUB_RUN_ID}"

      - name: Dockle Linter
        uses: erzz/dockle-action@v1.1.1
        with:
          image: "${{ env.IMAGE_ID }}"
          report-format: sarif
          exit-code: 1
          failure-threshold: 'WARN'

      - name: Vulnerability Scan
        uses: aquasecurity/trivy-action@0.0.20
        with:
          image-ref: "${{ env.IMAGE_ID }}"
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push $IMAGE_ID

      - name: Trigger IBM Toolchain
        if: github.ref == 'refs/heads/develop'
        env:
          CLOUD_API_KEY: ${{ secrets.CLOUD_API_KEY }}
        run: |
          curl -sL https://ibm.biz/idt-installer | bash
          ibmcloud login --apikey $CLOUD_API_KEY -r us-east
          ibmcloud dev tekton-trigger $TOOLCHAIN_ID --trigger-name 'CD Full Deploy Manual Trigger'

      - name: Post Slack Update
        if: ${{ failure() }}
        id: slack
        uses: slackapi/slack-github-action@v1.14.0
        with:
          payload: "{\"Repo\":\"${{ github.repository }}\",\"Workflow\":\"${{ github.workflow }}\",\"Branch\":\"${{ github.ref }}\",\"Link\":\"https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}\"}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
