name: PR

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency: pr-${{ github.ref }}

jobs:
  build:
    name: Vulnerability Checks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Vulnerability Check
      # override default -eo pipefail
      shell: bash --noprofile --norc {0}
      run: |
        wget -q -O nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.22/nancy-v1.0.22-linux-amd64
        chmod 555 nancy
        cd src
        go list -json -m all | ../nancy sleuth
        found=$?
        echo "VULNERABILITIES=$found" >> $GITHUB_ENV
        [[ "$found" == 1 ]] && echo "::error ::Vulnerabilities found."

    - uses: actions/github-script@v4
      if: ${{ env.VULNERABILITIES != 0 }}
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "Vulnerabilities found. See the 'PR -> Vulnerability Checks' logs for more details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          })
