name: PR

on:
  pull_request:
    types: [ opened, synchronize ]
  issue_comment: [ '**' ]

concurrency: pr-${{ github.ref }}

jobs:
  build:
    name: Vulnerability Checks
    # run if the PR was opened or there was a commit or comment containing '/pr_checks'
    if: ${{ (github.event_name == 'pull_request' && (github.event.action == 'opened' || contains(github.event.pull_request.body, '/pr_checks'))) || (github.event_name == 'issue_comment' && contains(github.event.comment, '/pr_checks'))  }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Check Dependencies
      # override default -eo pipefail
      shell: bash --noprofile --norc {0}
      run: |
        wget -q -O nancy https://github.com/sonatype-nexus-community/nancy/releases/download/v1.0.22/nancy-v1.0.22-linux-amd64
        chmod 555 nancy
        cd src
        go list -json -m all | ../nancy sleuth
        found=$?
        echo "VULNERABILITIES=$found" >> $GITHUB_ENV
        [[ "$found" == 1 ]] && echo "::error ::Vulnerabilities found in dependencies."

    - uses: actions/github-script@v4
      if: ${{ env.VULNERABILITIES != 0 }}
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "## ⚠️ Vulnerabilities found in dependencies.\nSee the 'PR -> Vulnerability Checks' logs for more details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          })

    - name: Unit Tests and Coverage
      run: |
        make
        # SonarCloud doesn't like the source code being in a sub directory,
        # so this moves all the source code into the base working directory 
        mv src/* ./

    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

